<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Kakaprodo\SystemAnalytic\Utilities\Util;
use Illuminate\Database\Migrations\Migration;

class CreateSystemAnalyticReportTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create((new (Util::persistModel()))->getTable(), function (Blueprint $table) {
            $table->id();
            $table->text('name')->comment('the analytic key name generated by custom data');
            $table->longText('value')->nullable()->comment('the serialized result');
            $table->string('analytic_type');
            $table->text('analytic_data')->comment('the serialized request inputs for this result');
            $table->dateTime('scope_start_date')->nullable();
            $table->dateTime('scope_end_date')->nullable();
            $table->string('group')->nullable()->comment('the group in which the analytic handler belongs to');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists((new (Util::persistModel()))->getTable());
    }
}
